// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

import { D1Database, Fetcher } from "@cloudflare/workers-types/experimental";

interface CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
}

export default CloudflareEnv;
