export enum SOPType {
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  CLINICAL = 'CLINICAL',
  FINANCIAL = 'FINANCIAL',
  OPERATIONAL = 'OPERATIONAL',
  COMPLIANCE = 'COMPLIANCE',
  MARKETING = 'MARKETING',
  TECHNICAL = 'TECHNICAL'
}
