export enum MaterialResourceType {
  EQUIPMENT = 'EQUIPMENT',
  SUPPLIES = 'SUPPLIES',
  FACILITIES = 'FACILITIES',
  TECHNOLOGY = 'TECHNOLOGY',
  HUMAN_RESOURCES = 'HUMAN_RESOURCES',
  FINANCIAL_RESOURCES = 'FINANCIAL_RESOURCES'
}
