export enum QuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  LIKERT_SCALE = 'LIKERT_SCALE',
  NUMERIC = 'NUMERIC',
  TEXT = 'TEXT',
  BOOLEAN = 'BOOLEAN',
  SCALE = 'SCALE',
  MATRIX = 'MATRIX',
  RANKING = 'RANKING'
}
